name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- #$NUMBER $TITLE @$AUTHOR"
sort-direction: "ascending"
categories:
  - title: "⚠️ Breaking changes"
    semver-increment: "major"
    when:
      - conventional:
          breaking: true
      - labels:
          - "breaking change"
  - title: "💡 Features"
    semver-increment: "minor"
    when:
      - conventional:
          types:
            - "feat"
            - "perf"
      - labels:
          - "feature"
          - "enhancement"
  - title: "🐛 Bug Fixes"
    when:
      - conventional:
          types:
            - "fix"
      - labels:
          - "bug"
  - title: "✏️ Documentation"
    when:
      - conventional:
          types:
            - "docs"
      - labels:
          - "documentation"
  - title: "🧰 Chore"
    when:
      - conventional:
          types:
            - "chore"
            - "build"
            - "ci"
            - "style"
            - "refactor"
            - "test"
      - labels:
          - "chore"
    collapse-after: 3

template: |
  ## Changes

  $CHANGES

  ## Contributors
  $CONTRIBUTORS

exclude-contributors:
  - "github-actions"

replacers:
  - search: '/(- #\d+) (?:feat|fix|docs|chore)!?:/g'
    replace: "$1"
  - search: '/(- #\d+) ([a-z])/g'
    replace: '$1 \u$2' # capitalize the first letter of each entry
