#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

PYTHON="python3"

if [ -x "$(command -v python3.13)" ]; then
  PYTHON="python3.13"
fi

if [ ! -n "$VIRTUAL_ENV" ]; then
  if [ -x "$(command -v uv)" ]; then
    uv venv venv
  else
    $PYTHON -m venv venv
  fi
  source venv/bin/activate
fi

if ! [ -x "$(command -v uv)" ]; then
  $PYTHON -m pip install uv
fi

script/bootstrap

pre-commit install
